### ISSUE TITLE
命令行模式异常

### ISSUE THREAD

**Issue by Crackersssss** [zhyipeng/yank-note-extension-vim-mode#3]
- 开始我以为只有部分不支持
    ![image](https://user-images.githubusercontent.com/45088781/172783159-8436ccdb-57ea-4220-8e51-b8ba41e4a617.png)
- 没想到。。。
    ![image](https://user-images.githubusercontent.com/45088781/172783210-3851ac8a-35fd-4468-8977-c7dbb56674bc.png)
    ![image](https://user-images.githubusercontent.com/45088781/172783239-7874ca75-cec4-4229-9ec9-5f98606189d1.png)

**Comment by zhyipeng** [comment]
monaco-vim 只是对 monaco 的 keymap 拓展而已, 本身没有实现对 vim 指令/宏的支持😂 , 加上这个模式主要是为了用它的搜索. 不过 monaco-vim 本身支持拓展, 可以考虑结合 yn 的 api 去支持一些 vim  的指令

**Comment by Crackersssss** [comment]
好吧，╮(╯-╰)╭
