### ISSUE TITLE
vim能否支持自定义vimrc 

### ISSUE THREAD

**Issue by simake2017** [zhyipeng/yank-note-extension-vim-mode#5]
vim 能否自定义vimrc 因为快捷键都经过了修改 ，能否使用指定vimrc

**Comment by zhyipeng** [comment]
上游插件只支持了 vim 的基础功能呢, 所以暂时还不能实现. 不过倒是提供了一定的拓展能力, 应该可以配合 yn 的 Action 玩出一点东西来, 你可以自己去研究下哈

**Comment by zhyipeng** [comment]
@simake2017 由于 yn 快捷键的改版, 目前插件最新版已经支持自定义 keymap, 采用类似 vscode vim 插件类似的配置方式 (配置文件), 其他 vimrc 相关功能暂未发现有需求.
